### PR TITLE
Add Kim as an author

### PR DESCRIPTION
**Pull request by kdaily**

### CODE REVIEW

**Comment by brucehoff** [comment]
The current PR changes 178 files.  Please update your branch from the Sage-Bionetworks 'develop' branch and then update your PR so that the 'diff' is just the requested authorship change.

**Comment by kdaily** [comment]
@brucehoff @kimyen 

I branched from develop - were there changes directly to master that weren't pulled in here?

**Comment by kdaily** [comment]
Looks like that's the case:

https://github.com/Sage-Bionetworks/synapser/compare/develop...master

**Comment by brucehoff** [comment]
> were there changes directly to master that weren't pulled in here?

Yes, but that shouldn't matter.  If you branch from develop and make a PR back into develop you should see just the changes you made in your branch.  N'est pas?

**Comment by kdaily** [comment]
I edited on Github directly, while on the develop branch, and this is what happened? I'll try again to verify.

**Comment by kdaily** [comment]
Huh. Don't know how this happened!

**Pull request closed without merging**
